import { useAuth } from "@/contexts/AuthContext";
import { useVoiceReminder } from "@/hooks/useVoiceReminder";
import { GEMINI_VOICES, VOICE_REMINDER_ROLES, BRIEFING_LANGUAGES, type BriefingLanguage } from "@/lib/voiceReminder";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Volume2, Square, Loader2, Play } from "lucide-react";

// Plays an AI voice briefing of the user's pending reminders (overdue leads,
// follow-ups, today's jobs, pending approvals) generated by Gemini TTS.
const VoiceReminderCard = () => {
  const { user } = useAuth();
  const { play, stop, loading, playing, script, voice, setVoice, language, setLanguage } = useVoiceReminder();

  if (!user || !VOICE_REMINDER_ROLES.includes(user.role as (typeof VOICE_REMINDER_ROLES)[number])) {
    return null;
  }

  return (
    <Card className="border-primary/20">
      <CardContent className="p-4">
        <div className="flex items-center gap-3 flex-wrap">
          <div className="w-10 h-10 rounded-full gradient-primary flex items-center justify-center text-primary-foreground shrink-0">
            <Volume2 className="w-5 h-5" />
          </div>
          <div className="flex-1 min-w-[180px]">
            <div className="font-semibold text-sm">Voice Briefing</div>
            <div className="text-xs text-muted-foreground">
              Gemini reads out your overdue leads, follow-ups & today's work
            </div>
          </div>
          <Select value={voice} onValueChange={setVoice} disabled={loading || playing}>
            <SelectTrigger className="w-[170px] h-9">
              <SelectValue placeholder="Voice" />
            </SelectTrigger>
            <SelectContent>
              {GEMINI_VOICES.map(v => (
                <SelectItem key={v.id} value={v.id}>{v.label}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          {playing ? (
            <Button variant="destructive" size="sm" className="gap-2" onClick={stop}>
              <Square className="w-4 h-4" /> Stop
            </Button>
          ) : (
            <Button size="sm" className="gradient-primary gap-2" onClick={play} disabled={loading}>
              {loading ? (
                <><Loader2 className="w-4 h-4 animate-spin" /> Preparing…</>
              ) : (
                <><Play className="w-4 h-4" /> Play briefing</>
              )}
            </Button>
          )}
        </div>
        {script && (
          <p className="mt-3 pt-3 border-t border-border text-sm text-muted-foreground whitespace-pre-wrap">
            {script}
          </p>
        )}
      </CardContent>
    </Card>
  );
};

export default VoiceReminderCard;
