// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's id, email, and OAuth client id for the current MCP session.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const info = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      client_id: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-my-leads.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function clientFor(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_leads_default = defineTool2({
  name: "list_my_leads",
  title: "List my leads",
  description: "List leads visible to the signed-in user, respecting RLS. Optionally filter by status and limit.",
  inputSchema: {
    status: z.string().optional().describe("Optional lead status filter (e.g. new, contacted, won, lost)."),
    limit: z.number().int().positive().optional().describe("Max rows to return. Default 25.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = clientFor(ctx);
    let q = supabase.from("leads").select("id, customer_name, phone, status, source, created_at, assigned_to").is("deleted_at", null).order("created_at", { ascending: false }).limit(Math.min(limit ?? 25, 100));
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-lead.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function clientFor2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_lead_default = defineTool3({
  name: "get_lead",
  title: "Get lead details",
  description: "Fetch a single lead by id, subject to the caller's row-level access.",
  inputSchema: { lead_id: z2.string().describe("UUID of the lead.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lead_id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await clientFor2(ctx).from("leads").select("*").eq("id", lead_id).is("deleted_at", null).maybeSingle();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return { content: [{ type: "text", text: "Lead not found or access denied" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/tools/list-service-jobs.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function clientFor3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_service_jobs_default = defineTool4({
  name: "list_service_jobs",
  title: "List service jobs",
  description: "List service and delivery jobs visible to the signed-in user (RLS applied). Optional status/type filters.",
  inputSchema: {
    status: z3.string().optional().describe("Job status filter (e.g. pending, assigned, on_route, completed)."),
    type: z3.string().optional().describe("Job type filter (service, delivery, self_delivery)."),
    limit: z3.number().int().positive().optional().describe("Max rows. Default 25.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, type, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = clientFor3(ctx).from("service_jobs").select("id, customer_name, address, status, type, date_to_attend, assigned_agent, description").is("deleted_at", null).order("date_to_attend", { ascending: true, nullsFirst: false }).limit(Math.min(limit ?? 25, 100));
    if (status) q = q.eq("status", status);
    if (type) q = q.eq("type", type);
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { jobs: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cdrgbhnntonyofqkhzpm";
var mcp_default = defineMcp({
  name: "omniflow-mcp",
  title: "OmniFlow MCP",
  version: "0.1.0",
  instructions: "OmniFlow (HDE) CRM tools for sales, service, and admin users. Use `whoami` to check the session, `list_my_leads` and `get_lead` for sales pipeline data, and `list_service_jobs` for dispatch/service work. All tools respect the caller's role and row-level access.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_my_leads_default, get_lead_default, list_service_jobs_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
